region_name       = "us-east-1"
vpc_cidr_block    = "10.0.0.0/16"
vpc_tag           = "VPC_Terra"
subnet_cidr_block = "10.0.1.0/24"
subnet_az         = "us-east-1a"
subnet_tag        = "Pub_Subnet_Terra"
igw_tag           = "Igw_Terra"
rt_cidr_block     = "0.0.0.0/0"
#ami               = "ami-091138d0f0d41ff90"
rt_tag = "RT_Terra"
#ec2_az            = "us-east-1a"
#ec2_type          = "t3.micro"
key_pair = "instance_keypair"

